const products = [
  {
    id: 1,
    name: "Wireless ",
    description: "Premium over-ear headphones with active noise cancellation and 30-hour battery life",
    price: 199.99,
    originalPrice: 249.99,
    rating: 4.8,
    reviewCount: 1245,
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&h=400&fit=crop",
    mainCategory: "electronics",
    category: "audio",
    inStock: true,
    isNew: false,
    discount: 20
  },
  {
    id: 2,
    name: '4K TV 55',
    description: "55-inch 4K Ultra HD Smart TV with HDR support and built-in streaming apps",
    price: 599.99,
    originalPrice: null,
    rating: 4.7,
    reviewCount: 892,
    image: "https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=400&h=400&fit=crop&auto=format",
    category: "tv",
    mainCategory: "electronics",
    inStock: true,
    isNew: true,
    discount: 0
  },
  {
    id: 3,
    name: "Gaming Mechanical Keyboard",
    description: "RGB backlit mechanical gaming keyboard with blue switches and programmable keys",
    price: 129.99,
    originalPrice: 159.99,
    rating: 4.6,
    reviewCount: 567,
    image: "https://images.unsplash.com/photo-1541140532154-b024d705b90a?w=400&h=400&fit=crop",
    category: "gaming",
    mainCategory: "electronics",
    inStock: false,
    isNew: false,
    discount: 0
  },
  {
    id: 4,
    name: "Smartphone 256GB",
    description: "Latest flagship smartphone with 256GB storage, triple camera system, and 5G connectivity",
    price: 899.99,
    originalPrice: 999.99,
    rating: 4.9,
    reviewCount: 2134,
    image: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=400&h=400&fit=crop",
    category: "phones",
    mainCategory: "electronics",
    inStock: true,
    isNew: false,
    discount: 10
  },
  {
    id: 5,
    name: "Wireless Charging Station",
    description: "3-in-1 wireless charging station for phone, earbuds, and smartwatch with fast charging",
    price: 79.99,
    originalPrice: 99.99,
    rating: 4.5,
    reviewCount: 423,
    image: "https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=400&h=400&fit=crop",
    category: "accessories",
    mainCategory: "electronics",
    inStock: true,
    isNew: true,
    discount: 20
  },
  {
    id: 6,
    name: "Laptop 15.6\" Core i7",
    description: "High-performance laptop with Intel Core i7, 16GB RAM, 512GB SSD, and dedicated graphics",
    price: 1299.99,
    originalPrice: 1499.99,
    rating: 4.7,
    reviewCount: 678,
    image: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=400&h=400&fit=crop",
    mainCategory: "electronics",
    category: "computers",
    inStock: true,
    isNew: false,
    discount: 13
  },
  {
    id: 7,
    name: "Smart Home Security Camera",
    description: "1080p HD wireless security camera with night vision, motion detection, and cloud storage",
    price: 89.99,
    originalPrice: 119.99,
    rating: 4.4,
    reviewCount: 834,
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop",
    mainCategory: "electronics",
    category: "security",
    inStock: true,
    isNew: false,
    discount: 25
  },
  {
    id: 8,
    name: "Bluetooth Portable Speaker",
    description: "Waterproof Bluetooth speaker with 360-degree sound and 24-hour battery life",
    price: 149.99,
    originalPrice: null,
    rating: 4.8,
    reviewCount: 1567,
    image: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=400&h=400&fit=crop",
    mainCategory: "electronics",
    category: "audio",
    inStock: true,
    isNew: true,
    discount: 0
  },
  {
    id: 9,
    name: "Gaming Mouse RGB",
    description: "High-precision gaming mouse with 16000 DPI sensor, RGB lighting, and programmable buttons",
    price: 69.99,
    originalPrice: 89.99,
    rating: 4.6,
    reviewCount: 456,
    image: "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=400&h=400&fit=crop",
    mainCategory: "electronics",
    category: "gaming",
    inStock: true,
    isNew: false,
    discount: 22
  },
  {
    id: 10,
    name: "Tablet 10.9\" 128GB",
    description: "10.9-inch tablet with A14 chip, 128GB storage, and support for Apple Pencil",
    price: 449.99,
    originalPrice: 499.99,
    rating: 4.7,
    reviewCount: 923,
    image: "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=400&h=400&fit=crop",
    mainCategory: "electronics",
    category: "tablets",
    inStock: true,
    isNew: false,
    discount: 10
  },
  {
    id: 11,
    name: "Smartwatch Fitness Tracker",
    description: "Advanced smartwatch with GPS, heart rate monitor, sleep tracking, and 7-day battery",
    price: 299.99,
    originalPrice: null,
    rating: 4.5,
    reviewCount: 1234,
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&h=400&fit=crop",
    mainCategory: "electronics",
    category: "wearables",
    inStock: true,
    isNew: true,
    discount: 0
  },
  {
    id: 12,
    name: "Wireless Earbuds Pro",
    description: "True wireless earbuds with active noise cancellation and premium sound quality",
    price: 179.99,
    originalPrice: 229.99,
    rating: 4.8,
    reviewCount: 2145,
    image: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=400&h=400&fit=crop",
    mainCategory: "electronics",
    category: "audio",
    inStock: true,
    isNew: false,
    discount: 22
  },
  {
    id: 13,
    name: "Electric Toothbrush Smart",
    description: "Smart electric toothbrush with app connectivity, pressure sensor, and multiple cleaning modes",
    price: 119.99,
    originalPrice: 149.99,
    rating: 4.6,
    reviewCount: 567,
    image: "https://images.unsplash.com/photo-1609840114035-3c981b782dfe?w=400&h=400&fit=crop",
    mainCategory: "electronics",
    category: "personal care",
    inStock: true,
    isNew: false,
    discount: 20
  },
  {
    id: 14,
    name: "Robot Vacuum Cleaner",
    description: "Smart robot vacuum with mapping technology, app control, and automatic dirt disposal",
    price: 399.99,
    originalPrice: 499.99,
    rating: 4.7,
    reviewCount: 789,
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop",
    mainCategory: "electronics",
    category: "home appliances",
    inStock: true,
    isNew: false,
    discount: 20
  },
  {
    id: 15,
    name: "Action Camera 4K",
    description: "Waterproof 4K action camera with image stabilization and wireless connectivity",
    price: 249.99,
    originalPrice: null,
    rating: 4.5,
    reviewCount: 345,
    image: "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=400&h=400&fit=crop",
    mainCategory: "electronics",
    category: "cameras",
    inStock: true,
    isNew: true,
    discount: 0
  },
  {
    id: 16,
    name: "USB-C Hub 7-in-1",
    description: "Multi-port USB-C hub with HDMI, USB 3.0, SD card reader, and PD charging support",
    price: 49.99,
    originalPrice: 69.99,
    rating: 4.4,
    reviewCount: 678,
    image: "https://images.unsplash.com/photo-1625842192804-7b0aca35d1ed?w=400&h=400&fit=crop",
    mainCategory: "electronics",
    category: "accessories",
    inStock: true,
    isNew: false,
    discount: 29
  },
  {
    id: 17,
    name: "Gaming Headset 7.1 Surround",
    description: "Professional gaming headset with 7.1 surround sound, noise-canceling mic, and RGB lighting",
    price: 99.99,
    originalPrice: 129.99,
    rating: 4.6,
    reviewCount: 834,
    image: "https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=400&h=400&fit=crop",
    mainCategory: "electronics",
    category: "gaming",
    inStock: true,
    isNew: false,
    discount: 23
  },
  {
    id: 18,
    name: "Smart Light Bulbs 4-Pack",
    description: "WiFi-enabled color-changing LED smart bulbs with voice control and scheduling features",
    price: 59.99,
    originalPrice: 79.99,
    rating: 4.3,
    reviewCount: 1456,
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop",
    mainCategory: "electronics",
    category: "smart home",
    inStock: true,
    isNew: false,
    discount: 25
  },
  {
    id: 19,
    name: "Portable Power Bank 20000mAh",
    description: "High-capacity power bank with fast charging, wireless charging pad, and LED display",
    price: 39.99,
    originalPrice: 54.99,
    rating: 4.5,
    reviewCount: 2345,
    image: "https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=400&h=400&fit=crop",
    mainCategory: "electronics",
    category: "accessories",
    inStock: true,
    isNew: false,
    discount: 27
  },
  {
    id: 20,
    name: "Drone with 4K Camera",
    description: "Professional drone with 4K camera, 3-axis gimbal, GPS, and 30-minute flight time",
    price: 799.99,
    originalPrice: 999.99,
    rating: 4.8,
    reviewCount: 456,
    image: "https://images.unsplash.com/photo-1473968512647-3e447244af8f?w=400&h=400&fit=crop",
    mainCategory: "electronics",
    category: "drones",
    inStock: true,
    isNew: false,
    discount: 20
  },
  {
    id: 31,
    name: "Classic White Button-Down Shirt",
    description: "Timeless cotton button-down shirt perfect for office wear and casual styling",
    price: 49.99,
    originalPrice: 69.99,
    rating: 4.6,
    reviewCount: 324,
    image: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=400&h=400&fit=crop",
    mainCategory: "clothing",
    category: "shirts",
    inStock: true,
    isNew: false,
    discount: 29
  },
  {
    id: 34,
    name: "Slim Fit Jeans",
    description: "Modern slim-fit jeans crafted from premium stretch denim for comfort and style",
    price: 79.99,
    originalPrice: 99.99,
    rating: 4.5,
    reviewCount: 445,
    image: "https://images.unsplash.com/photo-1542272604-787c3835535d?w=400&h=400&fit=crop",
    mainCategory: "clothing",
    category: "jeans",
    inStock: true,
    isNew: false,
    discount: 20
  },
  {
    id: 35,
    name: "Cashmere Sweater",
    description: "Luxurious 100% cashmere sweater with ribbed trim and contemporary fit",
    price: 179.99,
    originalPrice: null,
    rating: 4.7,
    reviewCount: 156,
    image: "https://images.unsplash.com/photo-1618932260643-eee4a2f652a6?w=400&h=400&fit=crop",
    mainCategory: "clothing",
    category: "sweaters",
    inStock: true,
    isNew: true,
    discount: 0
  },
  {
    id: 36,
    name: "Athletic Performance T-Shirt",
    description: "Moisture-wicking performance t-shirt designed for workouts and active lifestyle",
    price: 24.99,
    originalPrice: 34.99,
    rating: 4.4,
    reviewCount: 289,
    image: "https://images.unsplash.com/photo-1571945153237-4929e783af4a?w=400&h=400&fit=crop",
    mainCategory: "clothing",
    category: "activewear",
    inStock: true,
    isNew: false,
    discount: 29
  },
  {
    id: 38,
    name: "Floral Midi Skirt",
    description: "Romantic floral print midi skirt with flowing A-line silhouette and elastic waist",
    price: 54.99,
    originalPrice: null,
    rating: 4.3,
    reviewCount: 198,
    image: "https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=400&h=400&fit=crop",
    mainCategory: "clothing",
    category: "skirts",
    inStock: true,
    isNew: true,
    discount: 0
  },
  {
    id: 39,
    name: "Wool Blend Coat",
    description: "Classic double-breasted wool blend coat with tailored fit and luxurious finish",
    price: 219.99,
    originalPrice: 279.99,
    rating: 4.6,
    reviewCount: 167,
    image: "https://images.unsplash.com/photo-1539533113208-f6df8cc8b543?w=400&h=400&fit=crop",
    mainCategory: "clothing",
    category: "coats",
    inStock: true,
    isNew: false,
    discount: 21
  },
  {
    id: 40,
    name: "Striped Cotton Polo",
    description: "Classic striped cotton polo shirt with three-button placket and comfortable fit",
    price: 39.99,
    originalPrice: 49.99,
    rating: 4.2,
    reviewCount: 233,
    image: "https://images.unsplash.com/photo-1586790170083-2f9ceadc732d?w=400&h=400&fit=crop",
    mainCategory: "clothing",
    category: "polos",
    inStock: true,
    isNew: false,
    discount: 20
  },
  {
    id: 41,
    name: "High-Waisted Trousers",
    description: "Tailored high-waisted trousers with wide leg cut and professional finish",
    price: 89.99,
    originalPrice: null,
    rating: 4.7,
    reviewCount: 145,
    image: "https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=400&h=400&fit=crop",
    mainCategory: "clothing",
    category: "trousers",
    inStock: true,
    isNew: true,
    discount: 0
  },
  {
    id: 42,
    name: "Boho Maxi Dress",
    description: "Free-spirited boho maxi dress with intricate embroidery and flowing fabric",
    price: 94.99,
    originalPrice: 129.99,
    rating: 4.5,
    reviewCount: 189,
    image: "https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=400&h=400&fit=crop",
    mainCategory: "clothing",
    category: "dresses",
    inStock: true,
    isNew: false,
    discount: 27
  },
  {
    id: 43,
    name: "Merino Wool Cardigan",
    description: "Soft merino wool cardigan with button closure and versatile styling options",
    price: 129.99,
    originalPrice: 159.99,
    rating: 4.8,
    reviewCount: 98,
    image: "https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=400&h=400&fit=crop",
    mainCategory: "clothing",
    category: "cardigans",
    inStock: true,
    isNew: false,
    discount: 19
  },
  {
    id: 44,
    name: "Graphic Print Hoodie",
    description: "Trendy oversized hoodie with unique graphic print and comfortable cotton blend",
    price: 59.99,
    originalPrice: null,
    rating: 4.3,
    reviewCount: 267,
    image: "https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=400&h=400&fit=crop",
    mainCategory: "clothing",
    category: "hoodies",
    inStock: true,
    isNew: true,
    discount: 0
  },
  {
    id: 45,
    name: "Chino Shorts",
    description: "Classic chino shorts with perfect length and tailored fit for summer comfort",
    price: 34.99,
    originalPrice: 44.99,
    rating: 4.4,
    reviewCount: 312,
    image: "https://images.unsplash.com/photo-1591195853828-11db59a44f6b?w=400&h=400&fit=crop",
    mainCategory: "clothing",
    category: "shorts",
    inStock: true,
    isNew: false,
    discount: 22
  },
  {
    id: 47,
    name: "Jogger Sweatpants",
    description: "Comfortable fleece jogger sweatpants with tapered fit and elastic waistband",
    price: 44.99,
    originalPrice: null,
    rating: 4.2,
    reviewCount: 423,
    image: "https://images.unsplash.com/photo-1506629905962-3d8e67c7f7b1?w=400&h=400&fit=crop",
    mainCategory: "clothing",
    category: "sweatpants",
    inStock: true,
    isNew: true,
    discount: 0
  },
  {
    id: 48,
    name: "Cocktail Mini Dress",
    description: "Glamorous cocktail mini dress with sequin details and bodycon silhouette",
    price: 119.99,
    originalPrice: 149.99,
    rating: 4.7,
    reviewCount: 76,
    image: "https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=400&h=400&fit=crop",
    mainCategory: "clothing",
    category: "dresses",
    inStock: true,
    isNew: false,
    discount: 20
  },
  {
    id: 49,
    name: "Flannel Shirt",
    description: "Cozy flannel shirt in classic plaid pattern, perfect for layering",
    price: 49.99,
    originalPrice: 64.99,
    rating: 4.5,
    reviewCount: 298,
    image: "https://images.unsplash.com/photo-1588117472013-59bb13edafec?w=400&h=400&fit=crop",
    mainCategory: "clothing",
    category: "shirts",
    inStock: true,
    isNew: false,
    discount: 23
  },
  {
    id: 51,
    name: "Organic Extra Virgin Olive Oil",
    description: "Premium cold-pressed organic olive oil from Mediterranean groves, perfect for cooking and dressing",
    price: 24.99,
    originalPrice: 32.99,
    rating: 4.8,
    reviewCount: 412,
    image: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=400&h=400&fit=crop",
    mainCategory: "food",
    category: "oils",
    inStock: true,
    isNew: false,
    discount: 24
  },
  {
    id: 52,
    name: "Artisan Sourdough Bread",
    description: "Handcrafted sourdough bread with crispy crust and tender crumb, made with natural starter",
    price: 8.99,
    originalPrice: null,
    rating: 4.7,
    reviewCount: 234,
    image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400&h=400&fit=crop",
    mainCategory: "food",
    category: "bakery",
    inStock: true,
    isNew: true,
    discount: 0
  },
  {
    id: 53,
    name: "Wild Alaskan Salmon Fillet",
    description: "Fresh wild-caught Alaskan salmon fillet, sustainably sourced and rich in omega-3",
    price: 18.99,
    originalPrice: 24.99,
    rating: 4.9,
    reviewCount: 189,
    image: "https://images.unsplash.com/photo-1544943910-4c1dc44aab44?w=400&h=400&fit=crop",
    mainCategory: "food",
    category: "seafood",
    inStock: true,
    isNew: false,
    discount: 24
  },
  {
    id: 54,
    name: "Aged Parmesan Cheese",
    description: "24-month aged Parmigiano-Reggiano from Italy, perfect for pasta and grating",
    price: 16.99,
    originalPrice: null,
    rating: 4.8,
    reviewCount: 298,
    image: "https://images.unsplash.com/photo-1552767059-ce182ead6c1b?w=400&h=400&fit=crop",
    mainCategory: "food",
    category: "dairy",
    inStock: true,
    isNew: false,
    discount: 0
  },
  {
    id: 55,
    name: "Organic Quinoa",
    description: "Premium organic tri-color quinoa, gluten-free superfood packed with protein and nutrients",
    price: 12.99,
    originalPrice: 15.99,
    rating: 4.6,
    reviewCount: 367,
    image: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400&h=400&fit=crop",
    mainCategory: "food",
    category: "grains",
    inStock: true,
    isNew: true,
    discount: 19
  },
  {
    id: 56,
    name: "Himalayan Pink Salt",
    description: "Pure Himalayan pink rock salt, mineral-rich and perfect for cooking and finishing dishes",
    price: 9.99,
    originalPrice: 13.99,
    rating: 4.5,
    reviewCount: 445,
    image: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=400&h=400&fit=crop",
    mainCategory: "food",
    category: "spices",
    inStock: true,
    isNew: false,
    discount: 29
  },
  {
    id: 57,
    name: "Raw Manuka Honey",
    description: "Premium raw Manuka honey from New Zealand with UMF 15+ rating, natural antibacterial properties",
    price: 34.99,
    originalPrice: 44.99,
    rating: 4.9,
    reviewCount: 156,
    image: "https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=400&h=400&fit=crop",
    mainCategory: "food",
    category: "sweeteners",
    inStock: true,
    isNew: false,
    discount: 22
  },
  {
    id: 58,
    name: "Organic Avocados",
    description: "Fresh organic Hass avocados, perfectly ripe and creamy, packed with healthy fats",
    price: 6.99,
    originalPrice: null,
    rating: 4.4,
    reviewCount: 523,
    image: "https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?w=400&h=400&fit=crop",
    mainCategory: "food",
    category: "fruits",
    inStock: true,
    isNew: true,
    discount: 0
  },
  {
    id: 59,
    name: "Dark Chocolate 85%",
    description: "Premium Belgian dark chocolate with 85% cocoa content, rich and intense flavor",
    price: 7.99,
    originalPrice: 9.99,
    rating: 4.7,
    reviewCount: 289,
    image: "https://images.unsplash.com/photo-1481391319762-47dff72954d9?w=400&h=400&fit=crop",
    mainCategory: "food",
    category: "chocolate",
    inStock: true,
    isNew: false,
    discount: 20
  },
  {
    id: 60,
    name: "Grass-Fed Beef Ribeye",
    description: "Premium grass-fed ribeye steak, well-marbled and tender, perfect for grilling",
    price: 28.99,
    originalPrice: 35.99,
    rating: 4.8,
    reviewCount: 134,
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?w=400&h=400&fit=crop",
    mainCategory: "food",
    category: "meat",
    inStock: true,
    isNew: false,
    discount: 19
  },
  {
    id: 61,
    name: "Organic Baby Spinach",
    description: "Fresh organic baby spinach leaves, tender and nutrient-dense, perfect for salads",
    price: 4.99,
    originalPrice: null,
    rating: 4.3,
    reviewCount: 678,
    image: "https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=400&h=400&fit=crop",
    mainCategory: "food",
    category: "vegetables",
    inStock: true,
    isNew: true,
    discount: 0
  },
  {
    id: 62,
    name: "Premium Green Tea",
    description: "High-grade Japanese sencha green tea, antioxidant-rich with delicate flavor",
    price: 19.99,
    originalPrice: 26.99,
    rating: 4.6,
    reviewCount: 198,
    image: "https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=400&h=400&fit=crop",
    mainCategory: "food",
    category: "beverages",
    inStock: true,
    isNew: false,
    discount: 26
  },
  {
    id: 63,
    name: "Almond Butter",
    description: "Creamy organic almond butter, made from roasted almonds with no added oils or sugars",
    price: 14.99,
    originalPrice: 18.99,
    rating: 4.7,
    reviewCount: 324,
    image: "https://images.unsplash.com/photo-1571068316344-75bc76f77890?w=400&h=400&fit=crop",
    mainCategory: "food",
    category: "nuts",
    inStock: true,
    isNew: false,
    discount: 21
  },
  {
    id: 64,
    name: "Heirloom Tomatoes",
    description: "Colorful heirloom tomatoes, vine-ripened with complex flavors and perfect texture",
    price: 8.99,
    originalPrice: null,
    rating: 4.5,
    reviewCount: 267,
    image: "https://images.unsplash.com/photo-1592417817098-8fd3d9eb14a5?w=400&h=400&fit=crop",
    mainCategory: "food",
    category: "vegetables",
    inStock: true,
    isNew: true,
    discount: 0
  },
  {
    id: 65,
    name: "Coconut Oil",
    description: "Virgin coconut oil, cold-pressed and unrefined, perfect for cooking and baking",
    price: 11.99,
    originalPrice: 15.99,
    rating: 4.4,
    reviewCount: 456,
    image: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=400&h=400&fit=crop",
    mainCategory: "food",
    category: "oils",
    inStock: true,
    isNew: false,
    discount: 25
  },
  {
    id: 66,
    name: "Greek Yogurt",
    description: "Thick and creamy Greek yogurt, high in protein and probiotics, made from grass-fed milk",
    price: 5.99,
    originalPrice: 7.99,
    rating: 4.6,
    reviewCount: 589,
    image: "https://images.unsplash.com/photo-1571212515416-1e0c8ad3c3a4?w=400&h=400&fit=crop",
    mainCategory: "food",
    category: "dairy",
    inStock: true,
    isNew: false,
    discount: 25
  },
  {
    id: 67,
    name: "Artisan Coffee Beans",
    description: "Single-origin Ethiopian coffee beans, medium roast with fruity and floral notes",
    price: 22.99,
    originalPrice: null,
    rating: 4.8,
    reviewCount: 245,
    image: "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=400&h=400&fit=crop",
    mainCategory: "food",
    category: "beverages",
    inStock: true,
    isNew: true,
    discount: 0
  },
  {
    id: 68,
    name: "Pasta Linguine",
    description: "Authentic Italian durum wheat linguine pasta, bronze-cut for perfect sauce adhesion",
    price: 6.99,
    originalPrice: 8.99,
    rating: 4.5,
    reviewCount: 378,
    image: "https://images.unsplash.com/photo-1551892374-ecf8754cf8b0?w=400&h=400&fit=crop",
    mainCategory: "food",
    category: "pasta",
    inStock: true,
    isNew: false,
    discount: 22
  },
  {
    id: 69,
    name: "Mixed Berry Smoothie Pack",
    description: "Frozen organic mixed berries blend, perfect for smoothies and desserts",
    price: 9.99,
    originalPrice: 12.99,
    rating: 4.7,
    reviewCount: 423,
    image: "https://images.unsplash.com/photo-1506806732259-39c2d0268443?w=400&h=400&fit=crop",
    mainCategory: "food",
    category: "frozen",
    inStock: true,
    isNew: false,
    discount: 23
  },
  {
    id: 70,
    name: "Truffle Hot Sauce",
    description: "Gourmet truffle-infused hot sauce with medium heat and complex umami flavors",
    price: 16.99,
    originalPrice: 21.99,
    rating: 4.9,
    reviewCount: 167,
    image: "https://images.unsplash.com/photo-1594736797933-d0401ba2fe65?w=400&h=400&fit=crop",
    mainCategory: "food",
    category: "condiments",
    inStock: true,
    isNew: false,
    discount: 23
  }
]


export default products;
